### ISSUE TITLE
private_key support (Key pair auth)

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-snowflake#19]
This is one of 2 things holding back some users from using this tap. See https://github.com/transferwise/pipelinewise-tap-snowflake#key-pair-authentication

**Comment by haleemur** [comment]
@visch I'll take on development for this issue. I'm curious what the 2nd of the 2 things you allude to could be

**Comment by visch** [comment]
I shouldn't have left everyone hanging! I think I created an issue back when I said that and it is solved but I really don't know. This was specific to someone trying to use this target but was stuck from this feature being missing. The other might have been an ssh tunnel but that's a big guess
